version: '3.8'

services:
  upbit-mcp-server:
    build: .
    container_name: upbit-mcp-server
    ports:
      - "8001:8001"  # SSE 포트 매핑
    environment:
      - UPBIT_ACCESS_KEY=${UPBIT_ACCESS_KEY}
      - UPBIT_SECRET_KEY=${UPBIT_SECRET_KEY}
    volumes:
      - ./charts:/app/charts  # 차트 이미지 저장용 볼륨 마운트
      # 기존 Nginx와 공유할 차트 디렉토리 (기존 uploads 디렉토리 사용)
      - ../https-nginx-docker/uploads:/app/uploads  
    restart: unless-stopped
    networks:
      - nginx-n8n-net  # 기존 네트워크 사용

networks:
  nginx-n8n-net:
    external: true  # 기존 네트워크 사용

# 로컬 디렉토리 생성을 위한 참고
# mkdir -p ./charts